setup.py
The maintainer of json-subschema plans on keeping master working.
Once there is a released version of json-subschema we will switch over to using it
=> Change the json-subschema dependency to track master. 

lale/lib/sklearn/tfidf_vectorizer.py, test/test.py
by manually expanding for search space generators.  This could be supported more cleanly if we allowed  style references in our schemas.  Enable the (now passing) test_text_and_structured test
=> Encode the dependency between the min/max part of ngram_range 

lale/search/GridSearchCV.py, lale/search/search_space_grid.py, lale/sklearn_compat.py
This can be used by search backends to provide hints as to a good default to optimizers that support them.
=> Add support for mapping sklearn encoded parameters in a pipeline to their defaults

lale/operators.py
since this can break operators that are not copyable
=> Change make_operator to not clone the given impl

lale/lib/lale/hyperopt_classifier.py, lale/lib/lale/hyperopt_regressor.py, test/test_optimizers.py
The summary of the changes
- Added a runtime limit to the hyperopt optimization to work in conjunction with the limit on the number of evaluations
- Fixed the `.predict` function for hyperopt classifier/regressor to have the expected behavior (I think)
- Handle the updated use of the `make_scorer`/`get_scorer` API for `HyperoptRegressor`
I have also added/updated the test_optimizers.py to test these changes
=> Enhancements and fixes to the hyperopt classifier and regressor

lale/lib/lale/hyperopt_classifier.py, lale/lib/lale/hyperopt_regressor.py
This PR contains 2 changes:
- We allow the user to set the `best_score` in which case the `loss` is computed as `best_score - cv_score`. This makes the `loss >= 0` is `best_score` is correctly set. I am not entirely sure if this affect hyperopt at all but there are many black-box optimizers that perform better with positive objectives that they are trying to minimize rather than negative objectives that is being minimized. If the user does not specify the `best_score`, current behavior (which is equivalent to `best_score = 0` is preserved.
- Update `HyperoptRegressor` to allow user to specify the scorer similar to `HyperoptClassifier`.
=> Enabling user-specified scorer in HyperoptRegressor + best score

lale/operators.py
To take care of scikit like objects which do not follow all scikit conventions.
=> Changed clone to deepcopy for export_to_sklearn_pipeline

lale/operators.py, test/test_json_pretty_viz.py
This provides a way to get auto-generated enumerations values even if the names conflict with fields of the Operator class.
=> Add 'enum' property to operators.

lale/operators.py
There is no sklearn equivalent to Relational, so remove it during `export_to_sklearn_pipeline`.
=> Changes to export_to_sklearn_pipeline to handle Relational.

lale/docstrings.py, lale/expressions.py, lale/grammar.py, lale/helpers.py, lale/json_operator.py, lale/operator_wrapper.py, lale/operators.py, lale/pretty_print.py, lale/schema2enums.py, lale/schema_ranges.py, lale/schema_simplifier.py, lale/schema_utils.py, lale/schemas.py, lale/sklearn_compat.py, lale/type_checking.py, lale/visualize.py
`isort` module observed on the outer scripts. So that neither `search/*.py`, `lib/*.py`, `datasets/*.py`, and `utils/*.py` have been changed which means that the `schema2search_space.py` file is still like the usual.
=> Out Scripts are Optimized in the Importing Task

.github/workflows/build.yml, docs/index.rst, lale/lib/snapml/__init__.py, lale/lib/snapml/decision_tree_classifier.py, lale/lib/snapml/random_forest_classifier.py, lale/lib/snapml/random_forest_regressor.py, setup.py, test/test_snapml.py
Snap ML is now publicly available on Windows, Linux and Mac OS via `pip install snapml`. 
This is an initial pull request to replace the existing 3 pai4sk estimators with their equivalents in the new package.
=> Replace pai4sk with new publicly available snapml package

lale/lib/aif360/util.py
Fixes #596 
In the existing implementation of `fair_stratified_train_test_split`,  there is no argument for setting `random_state` and we internally just set its value to 42 when calling scikit learn's `train_test_split.`  It will be good idea to add this argument to the `fair_stratified_train_test_split` method similar to corresponding scikit routine.
=> Adding random_state argument to fair_stratified_train_test_split

docs/requirements.txt, lale/lib/aif360/README.md, lale/lib/autoai_libs/README.md, lale/lib/imblearn/README.md, lale/lib/lale/README.md, lale/lib/lightgbm/README.md, lale/lib/snapml/README.md, lale/lib/xgboost/README.md
Also, pinned docutils version for readthedocs to get nested lists to render properly again, following this work-around: https://github.com/sphinx-doc/sphinx/issues/9065.
=> Added README files to lale/lib packages to point to readthedocs.

lale/datasets/openml/openml_datasets.py, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Implemented code to pull the SpeedDating dataset from OpenML (https://www.openml.org/d/40536) in `lale.lib.aif360` and wrote tests to make sure that data can be pulled successfully and that preprocessed and non-preprocessed dataframes have expected structure and disparate impact.
For now, `samerace` and `importance_same_race` are being treated as protected attributes with privileged groups of `1` and `>= 8` respectively. This results in a disparate impact of 0.85. While this is within fairness bounds for group fairness based on best practices, it should be noted that models trained with this dataset may be individually unfair based on existing literature (https://www.researchgate.net/publication/341434281_Matchmaking_Under_Fairness_Constraints_a_Speed_Dating_Case_Study).
=> Contributing SpeedDating dataset from OpenML to AIF360 datasets

lale/datasets/__init__.py, lale/datasets/sklearn_to_pandas.py, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Wrapping Boston house price dataset from `sklearn.datasets` (https://scikit-learn.org/0.20/datasets/index.html#boston-house-prices-dataset) and placing it in `lale.lib.aif360`. In the process, I updated some tests in `test_aif360.py`. I mainly maintained old baselines and added some new tests based on those old baselines, but I also included a few TODOs about potential future test modifications.
=> Contributing Boston house price dataset to lale.lib.aif360

lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Leveraging AIF360 and some Python utility libraries to add portions of the MEPS dataset to `lale.lib.aif360`. Specifically, AIF360 includes 
> three versions of Medical Expenditure Panel Surveys (AHRQ, 2015; 2016).
(https://arxiv.org/pdf/1810.01943.pdf), the preprocessed forms of which are returned by the corresponding Lale methods. However, when preprocessing is not desired, some functionality of AIF360 is reproduced in Lale in order read from raw data directly. (Note that even in this case, some minimal preprocessing occurs, such as formatting of the "race" feature column and target column).
A few other things worth mentioning:
1. The Lale fetching code assumes the user has downloaded the corresponding .SSP (SAS transport) files from the MEPS website, converted them to .CSV files, and …
=> Contributing datasets corresponding to Panels 19, 20, and 21 from years 2015 and 2016 of the MEPS dataset

lale/datasets/openml/openml_datasets.py, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Adding some code to pull a dataset of passengers of the Titanic hosted on OpenML (https://www.openml.org/d/40945). The data can be used in a classification problem to predict which passengers survived, and given that women and children were given lifeboat priority, the dataset has quite noticeable disparate impact.
Note that another version of the Titanic dataset exists in OpenML with more runs (https://www.openml.org/d/40704), but the one used here has more features (and therefore may be better from a pipeline/processing standpoint). Also note that a `name` column results in a large dataframe when `preprocess=True` due to one-hot encoding. We may want to consider dropping that column in all cases if such data isn't useful in any circumstances.
=> Contributing Titanic dataset from OpenML

lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
This branch began as a quick fix to make sure `fetch_compas_df` respect a user's `preprocess` parameter choice (if provided). However, after poking around other parts of the code, it was determined that the COMPAS dataset compiled by ProPublica should be pulled from GitHub instead of OpenML for better comparability with other papers found in the literature. Moreover, up until now, we did not have code to pull the violent recidivism dataset that ProPublica's GitHub also provides. This has now been implemented as well.
Other major takeaways:
- For both COMPAS datasets, sex, race, and age are protected attributes ("Caucasian", "Female", and ">= 25" are privileged classes, although according to original ProPublica reports, COMPAS originally overpredicted recidivism scores for females; see …
=> Obtaining COMPAS recidivism and violent recidivism datasets from GitHub

docs/README-cn.md, docs/README-fr.md, docs/conf.py, docs/requirements.txt, lale/helpers.py, lale/lib/autogen/huber_regressor.py, lale/lib/imblearn/adasyn.py, lale/lib/imblearn/borderline_smote.py, lale/lib/imblearn/instance_hardness_threshold.py, lale/lib/imblearn/random_over_sampler.py, lale/lib/imblearn/smote.py, lale/lib/imblearn/smoteenn.py, lale/lib/imblearn/svm_smote.py, lale/lib/lale/halving_grid_search_cv.py, lale/lib/lightgbm/lgbm_classifier.py, lale/lib/lightgbm/lgbm_regressor.py, lale/lib/sklearn/multinomial_nb.py, lale/lib/sklearn/rfe.py, lale/lib/xgboost/xgb_regressor.py, lale/operators.py, lale/search/lale_smac.py, lale/search/search_space_grid.py, lale/settings.py
The documentation builds on readthedocs have been timing out and/or running out of memory. One of the big dependencies is tensorflow, so this PR removes that from docs/requirements.txt and adds it to autodoc_mock_imports in docs/conf.py instead. Locally, that seems to speed up the docs build from around 10 minutes to around 4 minutes. While doing these experiments, I also noticed that there is an excessive number of warnings during the docs build. This PR resolves many of the easy ones (e.g., caused by RST indentation issues).
=> Trying to fix documentation build problems

lale/datasets/openml/openml_datasets.py, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Title should be pretty self-explanatory. More information about the dataset (https://www.openml.org/d/26) can be found here: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.142.2022&rep=rep1&type=pdf
One paper (https://arxiv.org/pdf/2006.04292.pdf; corresponding code: https://github.com/yromano/fair_dummies/tree/master/data) uses this dataset to assert that trained models do not exploit the `finance` attribute when attempting to learn in a fair manner, but when I was determining what made sense for default `fairness_info` and preprocessing, I was not able to easily find features that resulted in unfair disparate impact when treating the problem as a binary classification one between "recommended" (in any capacity) and "not recommended". (e.g. `finance` actually is perfectly …
=> Adding Nursery dataset from OpenML with corresponding tests

docs/papers.rst, lale/lib/aif360/__init__.py, lale/lib/sklearn/_common_schemas.py, lale/lib/sklearn/dummy_classifier.py, lale/lib/sklearn/extra_trees_classifier.py, lale/lib/sklearn/random_forest_classifier.py
- updated papers.rst to mention the workshop papers at ICLR
- in the package documentation for lale.lib.aif360, moved datasets to their own header
- in ExtraTreesClassifier and RandomForestClassifier, added constraint against sparse labels
- in DummyClassifier, added missing schemas for predict_proba, and changed schemas for labels to allow boolean
=> Improvements to documentation and schemas.

lale/lib/autogen/calibrated_classifier_cv.py, lale/lib/autogen/elastic_net_cv.py, lale/lib/autogen/lars_cv.py, lale/lib/autogen/lasso_cv.py, lale/lib/autogen/lasso_lars_cv.py, lale/lib/autogen/logistic_regression_cv.py, lale/lib/autogen/multi_task_elastic_net_cv.py, lale/lib/autogen/multi_task_lasso_cv.py, lale/lib/autogen/orthogonal_matching_pursuit_cv.py, lale/lib/autogen/ridge_classifier_cv.py, lale/lib/autogen/ridge_cv.py, lale/lib/sklearn/__init__.py, lale/lib/sklearn/ada_boost_classifier.py, lale/lib/sklearn/ada_boost_regressor.py, lale/lib/sklearn/bagging_classifier.py, lale/lib/sklearn/bagging_regressor.py, lale/lib/sklearn/fit_spec_proxy.py, lale/lib/sklearn/stacking_classifier.py, lale/lib/sklearn/stacking_regressor.py, lale/lib/sklearn/stacking_utils.py, lale/lib/sklearn/voting_classifier.py, lale/lib/sklearn/voting_regressor.py, lale/operators.py, test/test_core_classifiers.py, test/test_core_regressors.py
Code here isn't necessarily final but the point of this pull request is to add and revise a few ensemble methods to make them compatible with Lale pipelines.
- Stacking: contributing `StackingClassifier` and `StackingRegressor` from scratch; overriding `_concatenate_predictions` 
to allow for pandas dataframe compatibility (sklearn by default converts to numpy arrays)
- Voting: contributing `VotingRegressor` from scratch and modifying `VotingClassifier` so that the latter has a `predict_proba` function (not exposed by default in sklearn but required by Lale post-mitigators)
- Bagging: contributing `BaggingRegressor` from scratch and modifying `BaggingClassifier` so that underlying estimators can receive pandas dataframes if provided (sklearn by default converts to numpy arrays)
- Tests …
=> Contributing Stacking ensembles and making changes to Voting and Bagging ensembles

lale/lib/sklearn/stacking_classifier.py, lale/lib/sklearn/stacking_regressor.py
Title pretty much explains it all. In the [PR that contributed `StackingClassifier` and `StackingRegressor`](https://github.com/IBM/lale/pull/713), I forgot to add `lale.docstrings.set_docstrings()` calls to make sure readthedocs info gets generated. Should be fixed in this PR.
=> Adding set_docstrings() function calls for Stacking ensembles to generate docs

lale/lib/autoai_libs/cat_encoder.py, lale/lib/autoai_libs/cat_imputer.py
Updating the `sklearn_version_family` of `lale.lib.autoai_libs.CatImputer` and `lale.lib.autoai_libs.CatEncoder` to allow all version families. As per the documentation of autoai_libs, this hyperparameter is ignored, so allowing more values to avoid errors.
=> Cat imputer

lale/lib/sklearn/stacking_utils.py
The helper method `_concatenate_predictions_pandas` written for Stacking ensembles has a bug when cross-validation techniques are used to partition data and when `passthrough=True`. As the code exists now, the cross-validation data, let's say `X_cv`, retains indices from the original `X` dataframe (and can be any value in `[0, X.shape[0]]`), but the predictions generated by each base estimator have indices corresponding to `range(X_cv.shape[0])`.
The join that happens in `pd.concat()` is an outer join that results in a ton of nans that throw errors, let alone a conceptually incorrect dataframe. This PR addresses the issue by forcing the row index of each set of predictions to be equivalent to that used by `X_cv` provided `passthrough=True`.
=> Fixing Stacking bug related to concatenating dataframes with cross-validation

lale/lib/sklearn/stacking_utils.py
Currently, if one of the base estimators produces predictions in the form of a pandas Series, it will crash because Series objects do not support `reshape()`. Converting to numpy array first to get around this issue.
=> Converting pd.Series to numpy array while concatenating predictions for Stacking

lale/lib/aif360/adversarial_debiasing.py, lale/lib/aif360/calibrated_eq_odds_postprocessing.py, lale/lib/aif360/eq_odds_postprocessing.py, lale/lib/aif360/gerry_fair_classifier.py, lale/lib/aif360/meta_fair_classifier.py, lale/lib/aif360/prejudice_remover.py, lale/lib/aif360/reject_option_classification.py, lale/lib/aif360/util.py
Adding `predict_proba` implementations by defining it on the base classes for in-estimator and post-estimator mitigators and raising errors or adding comments in cases where the function is not supported (currently `EqOddsPostprocessing`, `GerryFairClassifier`, and `RejectOptionClassification`).
Docstrings were updated as appropriate. No tests added because there is currently a lack of infrastructure around `predict` tests in general, plus some of these `predict_proba` functions are non-deterministic (as in the case of `CalibratedEqOdsPostprocessing`).
=> predict_proba implementations for supported AIF360 algorithms

lale/lib/aif360/util.py, lale/operators.py, test/test_aif360_ensembles.py
In order to use in-estimator mitigators like `PrejudiceRemover` and post-estimator mitigators like `CalibratedEqOddsPostprocessing` as part of Bagging and Boosting ensembles, the base estimator implementations require the `classes_` attribute on top of a `predict_proba` definition. [A prior PR](https://github.com/IBM/lale/pull/743) implemented `predict_proba`; this one handles the `classes_` attribute.
=> Making sure classes_ works for in-estimator and post-estimator mitigators

lale/lib/lightgbm/lgbm_classifier.py, lale/lib/lightgbm/lgbm_regressor.py
A collaborator carefully inspected the code and found that the constraint about `boosting_type,subsample_freq,subsample` was wrong. LightGBM checks this constraint in C++ code with a conjunction (`&&`), so after negation and push-down, that becomes a JSON Schema disjunction (`anyOf`). Besides fixing that mistake, this PR also includes a couple of other cleanups. One is to add the same constraints to `LGBMRegressor`; previously they were only in `LGBMCLassifier`. The other is to shred the documentation of `boosting_type` into the separate enum constants so the automatically generated documentation on readthedocs looks a little nicer.
=> Fixing a mistake in the second schema constraint for LightGBM.

examples/demo_help_and_errors.ipynb, lale/docstrings.py, lale/lib/sklearn/dummy_classifier.py, lale/lib/sklearn/dummy_regressor.py, lale/lib/sklearn/logistic_regression.py, lale/operators.py
- Minor wording tweaks in schema error messages to be more understandable.
- Fixed mistake in docstrings for unions, which should only prepend "or" at the top-level items.
- Added "and" in docstrings for top-level items of intersections.
- Added missing schema constraints to DummyClassifier and DummyRegressor.
- Split the documentation for the strategy of DummyClassifier and DummyRegressor so each enum constant can have its own description attached, and to exclude some constants from the optimizer.
=> Improvements to error messages and documentation.

.github/workflows/build.yml
Temporarily removed `test/test_autoai_ts_libs.py` from the test matrix until the following error is addressed:
```
_________________ ERROR collecting test/test_autoai_ts_libs.py _________________
ImportError while importing test module '/home/runner/work/lale/lale/test/test_autoai_ts_libs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
test/test_autoai_ts_libs.py:28: in <module>
from lale.lib.autoai_ts_libs import (  # type: ignore # noqa; StandardRowMeanCenterMTS,; WindowTransformerMTS; DifferenceFlattenAutoEnsembler,; FlattenAutoEnsembler,; LocalizedFlattenAutoEnsembler, …
```
=> Disabling autoai_ts_libs tests.

.github/workflows/build.yml, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Upon trying to run a grid search with all in-estimator mitigators against all datasets (new and old), I ran into some runtime issues against the newer datasets based on the preprocessing steps that were taken. As a result, this PR contains some modifications to preprocessing steps that should help all algorithms run to completion and properly fit models. Specifically:
* COMPAS and COMPAS Violent: reduce number of categorical columns and binarize via grouping attributes
* SpeedDating: removing categorical columns and removing columns that would otherwise lead to dataset leakage
* Titanic: removing categorical columns
* TAE: relaxing fairness info to allow for more positive examples in privileged group while training
* Boston: discouraging public use of dataset based on issues described in …
=> Several modifications to new(er) datasets

lale/lib/aif360/datasets.py, test/test_aif360.py
Shifting `fairness_info` to only care about `sex` instead of both `sex` and `age` to hopefully make fitting models easier.
=> Relaxing fairness_info for Titanic dataset

lale/lib/sklearn/stacking_utils.py
Specifically with a `MetaFairClassifier` as a base estimator for a StackingClassifier while trying to fit the SpeedDating dataset, the base estimator produces a NaN value for one of the predictions, which causes a downstream data-checking assert to fail and throws off downstream computations. This PR modifies the `_concatenate_predictions_pandas` method to replace NaN values with 0 in the rare case that this should happen (if at all). (Feel free to decline if there is a better solution.)
=> Fix to Stacking in case a base estimator produces a NaN value

lale/lib/sklearn/bagging_classifier.py, lale/lib/sklearn/bagging_regressor.py, lale/lib/sklearn/column_transformer.py, lale/lib/sklearn/extra_trees_classifier.py, lale/lib/sklearn/extra_trees_regressor.py, lale/lib/sklearn/feature_agglomeration.py, lale/lib/sklearn/function_transformer.py, lale/lib/sklearn/gaussian_nb.py, lale/lib/sklearn/k_neighbors_classifier.py, lale/lib/sklearn/k_neighbors_regressor.py, lale/lib/sklearn/linear_svc.py, lale/lib/sklearn/linear_svr.py, lale/lib/sklearn/logistic_regression.py, lale/lib/sklearn/min_max_scaler.py, lale/lib/sklearn/missing_indicator.py, lale/lib/sklearn/one_hot_encoder.py, lale/lib/sklearn/ordinal_encoder.py, lale/lib/sklearn/random_forest_classifier.py, lale/lib/sklearn/random_forest_regressor.py, lale/lib/sklearn/ridge.py, lale/lib/sklearn/ridge_classifier.py, lale/lib/sklearn/robust_scaler.py, lale/lib/sklearn/simple_imputer.py, lale/lib/sklearn/svc.py, lale/lib/sklearn/svr.py, test/test_core_classifiers.py, test/test_optimizers.py, test/test_type_checking.py
- BaggingClassifier - Add 2 constraints.
- BaggingRegressor - Add 2 constraints.
- ColumnTransformer - Add a sparse constraint.
- ExtraTreesClassifier - Add a constraint.
- ExtraTreesRegressor - Add 2 constraints.
- FeatureAgglomeration - Add a sparse constraint.
- FunctionTransformer - Fix a constraint.
- GaussianNB - Add a sparse constraint.
- KNeighborsClassifier - Remove 2 constraints (false negatives).
- KNeighborsRegressor - Remove 2 constraints (false negatives).
- For KNN-C and KNN-R, this constraint might be useful but the schema is long and contains many TODOs.
> Metric 'minkowski' not valid for sparse input. Use sorted(sklearn.neighbors.VALID_METRICS_SPARSE['brute']) to get valid options. Metric can also be a callable function.
- LinearSVC - Improve constaints.
- LinearSVR - …
=> Improve Lale sklearn schema

lale/operators.py, test/test_json_pretty_viz.py
diff() feature takes an operator and generates a diff with the other operator. Useful when modifying an existing pipeline through customize_schema or the (upcoming) replace() feature and examining what changed. By default, displays Markdown diff for notebooks. 
Tests were added to tests/test_json_pretty_viz.py
=> diff() feature with tests

lale/operators.py, test/test_core_pipeline.py, test/test_replace.py
Adds replace() function for BasePipeline that takes an original operator and replaces with a given replacement operator throughout. Currently works for simple pipelines and pipelines with Choice operators. Includes tests in test/test_core_pipeline.py
=> replace() function for pipelines

lale/lib/snapml/snap_svm_classifier.py
Check if Snap ML > 1.8.0 is installed, and if so add the 'loss' hyper-parameter to the SnapSVMClassifier
=> Add loss to schema for SnapSVMClassifier for snapml>1.8.0

lale/expressions.py, lale/helpers.py, lale/lib/lale/map.py, lale/lib/rasl/_eval_pandas_df.py, lale/lib/rasl/_eval_spark_df.py, test/test_relational.py
Add a pass in the `Map` operator that validate the expression to map before executing it. It allows early and uniform error detection independent of the backend.
=> Expression validator in Map

lale/operators.py, test/test_replace.py
Allows for targeting a choice operator for replacement in replace(). Includes new test in test/test_replace
For example:
```Python
choice = PCA | SelectKBest
pipeline = choice >> LogisticRegression
replaced_pipeline = pipeline.replace(choice, NoOp)
```
Resulting pipeline should be:
```Python
NoOp >> LogisticRegression
```
=> Allow for replacing choice operator in replace()

lale/pretty_print.py
Current pretty_print code relied on string join for generating the output with combinators. i.e. `f" {combinator} ".join(printed_steps.values())`. This breaks when there is only one step in the pipeline. This PR adds a check for this condition and uses `make_pipeline` to generate the output string instead.
=> use make_pipeline in `pretty_print` of a pipeline with a single node.

lale/lib/rasl/map.py
In lale.lib.rasl._Accuracy, we create a column name subscript using `get_columns(y_true)[0]`. This created a column name `0` which was type `int` in lale.lib.rasl.map.visit_Subscript. The PR adds a check for type str before calling `strip`.
=> Fixing map to allow integer column names.

lale/lib/aif360/util.py, lale/lib/rasl/_task_graphs.py, lale/lib/rasl/metrics.py, test/test_aif360.py, test/test_relational_sklearn.py
Between the batched metrics in lale.lib.rasl and lale.lib.aif360, there were three types of batches: `(X, y)` vs. `(y_true, y_pred)` vs. `(y_true, y_pred, X)`. Added type annotations to clarify which methods use which batch type. Also, made sure that the same method in different metrics have the same signatures.
=> Harmonizing batched metrics APIs.

lale/datasets/openml/openml_datasets.py
Hello, currently when fetching datasets from openml, the dataset is split into train and test using a fixed seed 0 - if one re- does an AutoML experiment several times, it would be useful if the seed could be set each time separately.
=> adding seed as a param

lale/operators.py, test/test_core_pipeline.py
This option allows users to call `partial_fit` on a trained pipeline without explicitly freezing the prefix. This PR also makes `partial_fit` on a TrainedPipeline such that it does not mutate the original object. This matches our `fit` implementation.
=> Added an option `freeze_trained_prefix` to partial_fit of pipelines.

lale/type_checking.py
Use `Iterable` from `collections.abc` - importing abstract base classes straight from `collections` is not supported in Python 3.10 and above...
Signed-off-by: DanielRyszkaIBM <daniel.ryszka@pl.ibm.com>
=> Use Iterable from collections.abc

.github/workflows/build.yml, lale/lib/xgboost/xgb_classifier.py, lale/lib/xgboost/xgb_regressor.py, setup.py
When trying to use XGBoost estimators from xgboost>=1.6, I've encountered the following issue when trying to import simple initialized estimator usgin `lale.helpers.import_from_sklearn_pipeline`:
- code example:
```
m = XGBRegressor()
m_l = import_from_sklearn_pipeline(m)
...
```
- error encountered:
```
Invalid configuration for XGBRegressor(objective='reg:squarederror', base_score=None, booster=None, callbacks=None, colsample_bylevel=None, colsample_bynode=None, colsample_bytree=None, early_stopping_rounds=None, enable_categorical=False, eval_metric=None, gamma=None, gpu_id=None, grow_policy=None, importance_type=None, interaction_constraints=None, learning_rate=None, max_bin=None, max_cat_to_onehot=None, max_delta_step=None, max_depth=None, max_leaves=None, min_child_weight=None, …
```
=> Fix schemas for XGBoost >= 1.6

lale/lib/sklearn/simple_imputer.py, lale/lib/xgboost/xgb_classifier.py, lale/lib/xgboost/xgb_regressor.py
Fix the following two issues when call `import_from_sklearn_pipeline`:
1. scikit learn 1.1.1
```
jsonschema.exceptions.ValidationError: Invalid configuration for SimpleImputer(add_indicator=False, copy=True, fill_value=None, missing_values=float('nan'), strategy='mean', verbose='deprecated') due to invalid value verbose=deprecated.
Some possible fixes include:
- set verbose=0
Schema of argument verbose: {
"type": "integer",
"default": 0,
"description": "Controls the verbosity of the imputer.",
}
Invalid value: deprecated
```
2. xgboost 1.6.2
```
jsonschema.exceptions.ValidationError: Invalid configuration for XGBRegressor(objective='reg:squarederror', base_score=0.5, booster='gbtree', callbacks=None, colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1, early_stopping_rounds=None, …
```
=> Support scikit learn 1.1 and xgboost 1.6

lale/operators.py
Otherwise, cannot call fit on a pipeline that contains such a Project operator.
=> Work-around for calling fit on Project with static coluns after clone.

lale/expressions.py, lale/lib/rasl/_eval_pandas_df.py, lale/lib/rasl/_eval_spark_df.py, lale/lib/rasl/min_max_scaler.py, test/test_relational.py, test/test_relational_sklearn.py
=> Generalized ite(cond, v1, v2) function to allow non-constant v1 and v2 and used that to implement the clip option of lale.lib.rasl.MinMaxScaler.

.github/workflows/build.yml
=> only run test_autoai_output_consumption on 3.8 and 3.9

.github/workflows/build.yml
Install autoai_libs when testing the demo notebooks
=> Use a newer version of autoai_libs on pypi for Python 3.9 and 3.10.

lale/lib/aif360/adversarial_debiasing.py, lale/lib/aif360/datasets.py, lale/lib/aif360/fair_smote.py, lale/lib/aif360/util.py, lale/lib/imblearn/_common_schemas.py, lale/lib/imblearn/borderline_smote.py, lale/lib/imblearn/smote.py, lale/lib/imblearn/smoten.py, lale/lib/imblearn/smotenc.py, lale/lib/imblearn/svm_smote.py
- suppress spurious tensorflow warnings
- option to preprocess only y for TAE dataset
- forward SMOTE hyperparameters from FairSMOTE
- better error message from post-estimator mitigators
- documentation typo
=> Miscellaneous minor fixes in lale.lib.aif360 and lale.lib.imblearn.

lale/lib/aif360/_mystic_util.py, lale/lib/aif360/urbis.py, pylintrc, setup.py, test/test_aif360.py
Using `mystic` solver from corresponding Python package to implement `_pick_sizes` for downsampling via Urbis. Also wrote a few unit tests to evaluate functionality and some utility functions that can be extended for upsampling via Orbis and (potentially) mixed sampling (i.e., both upsampling and downsampling).
=> Urbis Mystic Implementation

lale/__init__.py
- Add support for Python 3.11
- The SMAC hyperoptimization backend is not currently supported on 3.11
- Add support for scikit-learn 1.3 and 1.4
- Update supported versions of numpy, scipy, pandas, xgboost, lightgbm, snapml, and tensorflow
- AIF360 does not currently support numpy>=1.24, so testing for aif360 libraries is done using an older version of numpy
- Fix readthedocs build so our documentation is correctly updated
- Add label encoding to our wrapper for XGBClassifier, since it longer does this.
- Shuffle data in some batching tests to (mostly) avoid problems with encoding
- Remove support for Python 3.7 and scikit-learn < 1.0
- Remove autoai_libs wrappers and tests (they have been moved into the autoai_libs package).
=> Increment lale version to 0.8.0

lale/__init__.py
* Fix for xgb classifier without a label encoder
* URL links fix to open them in new tab
* Use newer AIF360 version that does not require an upper bound on numpy version
=> Increment lale version to 0.8.1

lale/__init__.py
Maintenance release that supports newer versions of dependencies.
- Add support for Python 3.12
- Add support for Numpy>=2.0
- Support newer versions of dependencies:
- imbalanced-learn: 0.13
- XGBoost: 3.0
- lightgbm: 4.6
- SnapML: 1.16
- scikit-learn: 1.6
- Improvements to test datasets
- Replace use of no longer available dataset
- Enable support for prefetching and caching datasets in CI
- Update all static tools
Removals/Known Issues:
- Remove support for Python 3.8 and Python 3.9
- Python 3.9 is still believed to work , but it is no longer tested as part of CI and hence no longer supported.
- Disable testing for RASL subsystem.
- It should still work with older versions of Numpy and Python, however it currently breaks with newer versions
- This breakage will hopefully be fixed, and …
=> Increment lale version to 0.9.0

lale/__init__.py
Dependency updates:
* Make graphviz dependency optional
* Increase upper bound on jsonschema
* Upper bound pyspark dependency to < 4.0
* Support newer versions of numpy
* Add autoai-fairness dependency set with appropriate version bounds on depdendencies
=> Increment lale version to 0.9.1
