IBM/lale

lale/schema_simplifier.py
=> Fix schema simplifier to handle unhashable enumeration values

lale/schema_simplifier.py, lale/schema_utils.py, lale/search/schema2search_space.py
Since using True and False breaks validators, since they are not technically legal schemas
=> Use {} and {"not":{}} instead of True and False for schemas.

lale/schema_simplifier.py, lale/schema_utils.py, lale/search/schema2search_space.py, lale/search/search_space.py
when the default is a valid member of the search space
=> Only add defaults to search spaces 

lale/lib/lale/grid_search_cv.py, lale/lib/lale/hyperopt.py
The input/output schemas for the optimizers and for Logistic Regression were overly strict
=> Relax optimizer schemas

lale/operators.py, lale/sklearn_compat.py
and make sure they are not pickled
=> Change how auto-derived enumerations are implemented

lale/search/lale_hyperopt.py, lale/search/schema2search_space.py, lale/search/search_space.py, lale/search/search_space_grid.py
enabling more flexible search spaces
=> Merge SearchSpaceList and SearchSpaceArray,

lale/search/search_space.py, lale/search/search_space_grid.py, lale/sklearn_compat.py, test/test_core_operators.py
Extend sklearn compatible encoding conventions to handle them.
=> Add support for lists and tuples to grid based backends.  

lale/search/lale_grid_search_cv.py, lale/search/lale_smac.py, lale/search/op2hp.py, lale/search/schema2search_space.py, lale/search/search_space.py, lale/search/search_space_grid.py
allowing IR for different representations of the search space to be printed
=> Enhance support for LALE_PRINT_SEARCH_SPACE

lale/operators.py, test/test_core_operators.py
=> Add special (improved) exception messages when summary is called incorrectly

lale/lib/sklearn/pca.py
Fixes https://github.com/IBM/lale/issues/609
=> Removed PCA constraint "Option tol can be set for svd_solver arpack."

lale/lib/aif360/util.py, test/test_aif360.py
=> Fixes issue #610.

.github/workflows/build.yml, lale/lib/lale/baseline_classifier.py, lale/lib/lale/baseline_regressor.py, lale/lib/lightgbm/lgbm_classifier.py, lale/lib/lightgbm/lgbm_regressor.py, lale/lib/sklearn/__init__.py, lale/lib/sklearn/_common_schemas.py, lale/lib/sklearn/ada_boost_classifier.py, lale/lib/sklearn/ada_boost_regressor.py, lale/lib/sklearn/dummy_classifier.py, lale/lib/sklearn/dummy_regressor.py, lale/lib/sklearn/variance_threshold.py, lale/lib/xgboost/xgb_classifier.py, lale/lib/xgboost/xgb_regressor.py, lale/operators.py, test/test_aif360.py, test/test_core_classifiers.py, test/test_core_misc.py, test/test_core_pipeline.py, test/test_core_regressors.py, test/test_core_transformers.py
Replacing BaselineClassifier with DummyClassifier from Sklearn.
Relacing BaselineRegressor with DummyRegressor from Sklearn.
Created new operator with make_operator with schemas defined in BaselineClassifier and BaselineRegressor
Contributed by students of SRH University, Heidelberg.
https://github.com/tauseefhashmi
https://github.com/frankcode101
https://github.com/tanmaygaikwad
https://github.com/RajathReddy9
https://github.com/vickyvishal/
=> replace BaselineClassifier/Regressor by DummyClassifier/Regressor. Issue #618

lale/operators.py, test/test_core_misc.py
=> Revert "Better error message when fit is called on a PlannedOperator."

lale/datasets/openml/openml_datasets.py, lale/lib/aif360/__init__.py, lale/lib/aif360/datasets.py, test/test_aif360.py
Pretty much what the title says. The Teaching Assistant Evaluation (TAE) dataset (https://www.openml.org/d/48) consists of 151 TA evaluations from the University of Wisconsin--Madison. According to the paper that contributed it,
> The highly significant Pvalue for the Semester variable is expected because summer teaching assignments
are normally awarded to the better TAs.
(see page 23 of http://www3.stat.sinica.edu.tw/statistica/oldpdf/A7n41.pdf)
Native-English-speaking TAs were also found to receive higher ratings relative to their counterparts. To that end, both are treated as privileged groups when calculating disparate impact, which is 0.347.
=> Contributing Teaching Assistant Evaluation (TAE) dataset from OpenML and adding corresponding tests.

.codecov.yml, .github/workflows/build.yml, README.md
This reverts commit 2e04aa286009b11a9a448ec860846aa11bbc1b9e.
=> Revert "remove use of codecov for now"

lale/lib/lale/join.py
validate_hyperparams instead of in the constructor
=> Change the Join operator to validate its hyperparameters using

lale/lib/lale/join.py, test/test_relational.py
@kiran-kate Please review and merge.
This PR majorly includes the following changes:
- Made error logs more descriptive
- Added more validation conditions in the test cases
- Changed the way go_sales dataset is read to make it more robust.
=> Modified error logs to make them more descriptive and other minor changes

lale/docstrings.py
=> Eliding top-level "dict of" from hyperparam constraints alternatives.

examples/demo_help_and_errors.ipynb, lale/operators.py, test/test_type_checking.py
Addresses https://github.com/IBM/lale/issues/726
=> Suggest hyperparam fixes when hyperparams don't validate against the schema

examples/demo_help_and_errors.ipynb, lale/docstrings.py, lale/operators.py, test/test_type_checking.py
Fixes issue #722.
Fixes issue #750.
=> Links to documentation of hyperparameter constraints.

lale/lib/autoai_ts_libs/__init__.py, lale/lib/autoai_ts_libs/difference_flatten_auto_ensembler.py, lale/lib/autoai_ts_libs/flatten_auto_ensembler.py, lale/lib/autoai_ts_libs/localized_flatten_auto_ensembler.py, test/test_autoai_ts_libs.py
Tried to add more test cases for auto ensemblers from autoai-ts-libs. They don't work as of now, but keeping them commented out as autoai-ts-libs is supposed to fix it.
=> Trying to add more tests for autoai_ts_libs

lale/lib/lale/both.py, lale/lib/lale/grid_search_cv.py, lale/lib/lale/halving_grid_search_cv.py, lale/lib/lale/hyperopt.py, lale/lib/lale/identity_wrapper.py, lale/lib/lale/observing.py, lale/lib/lale/smac.py, lale/lib/lale/topk_voting_classifier.py, lale/lib/sklearn/pipeline.py, lale/operators.py, test/mock_custom_operators.py, test/test_core_misc.py
=> Add support for predict parameters. 

lale/lib/lale/__init__.py, lale/lib/lale/observing.py, lale/lib/lale/tee.py, test/test_core_misc.py
that simplifies observing data passing through a pipeline
=> Add a Tee operator for debugging/logging

lale/helpers.py, lale/lib/lale/batching.py
=> num_workers in batching, worker_init_fn in create_data_loader

lale/lib/lale/optimize_suffix.py
=> Fix OptimizeSuffix predict so that it correctly passes on predict

lale/datasets/data_schemas.py, lale/helpers.py, lale/lib/lale/__init__.py, lale/lib/lale/functions.py, lale/lib/lale/join.py, lale/lib/lale/split_xy.py, test/test_relational.py
=> Added code for Split_Xy operator

lale/lib/autogen/bernoulli_nb.py
- add a constraint.
- modify relevantToOptimizer list.
- modify "binarize" schema.
- add "classifier" tag.
=> Improve BernoulliNB autogen schema

lale/lib/imblearn/instance_hardness_threshold.py, lale/lib/lale/_common_schemas.py, lale/lib/lale/auto_pipeline.py, lale/lib/lale/grid_search_cv.py, lale/lib/lale/halving_grid_search_cv.py, lale/lib/lale/hyperopt.py, lale/lib/lale/smac.py, lale/lib/lale/topk_voting_classifier.py, lale/lib/sklearn/stacking_classifier.py, lale/lib/sklearn/stacking_regressor.py
Prepare for optimizers that take multiple scorers
=> Factor out and rationalize more of the schemas used in optimizers.

setup.py
This changes provide option to install lale with only libraries needed to use 'fairness'.
=> Add support for lale installation with only 'fairness' 

lale/operators.py, test/test_core_pipeline.py
Assign `_hyperparams` in `convert_to_trained`.
=> Fix convert_to_trained.

lale/lib/autoai_libs/cat_imputer.py, lale/lib/autoai_libs/num_imputer.py
=> version gated updates to enhance the autoai_libs NumImputer and CatImputer schemas

lale/lib/rasl/min_max_scaler.py, lale/lib/sklearn/min_max_scaler.py, test/test_relational_sklearn.py
Add `partial_fit` and test `get_params`
=> Add more functions to the RASL MinMaxScaler implementation

lale/operators.py, test/test_core_misc.py
(and getting the default from the anyOf when applicable)
=> add support for gathering multiple (anyOf) enums in get_param_ranges 

lale/grammar.py, lale/helpers.py, lale/json_operator.py, lale/lib/autoai_libs/util.py, lale/lib/lale/optimize_last.py, lale/operators.py, lale/search/schema2search_space.py, test/test_core_misc.py, test/test_core_pipeline.py, test/test_optimizers.py, test/test_relational_sklearn.py
Rename old method to steps_list
=> Change pipeline steps to be a sklearn compatible property

lale/lib/imblearn/all_knn.py, lale/lib/imblearn/condensed_nearest_neighbour.py, lale/lib/imblearn/edited_nearest_neighbours.py, lale/lib/imblearn/instance_hardness_threshold.py, lale/lib/imblearn/repeated_edited_nearest_neighbours.py
Fix possible values of 'sampling_strategy' of 5 Imblearn's Under-sampling methods, from "minority" to "majority".
=> Fix values of 'sampling_strategy' in 5 Imblearn's methods

lale/operators.py
=> Add steps property for OperatorChoice, as for operator

lale/lib/lale/project.py, test/test_relational.py, test/test_type_checking.py
when transforming spark and pandas data
=> Use Map as backend for Project

.pre-commit-config.yaml, lale/datasets/data_schemas.py, lale/lib/rasl/_eval_pandas_df.py, lale/lib/rasl/_eval_spark_df.py, lale/lib/rasl/scores.py, test/test_relational.py
Minor formatting changes due to black version change.
=> Re-enable black and update some pre-commit tool versions.

.pre-commit-config.yaml, lale/datasets/multitable/util.py, lale/lib/aif360/datasets.py, lale/lib/aif360/util.py, lale/lib/dataframe.py, lale/lib/rasl/functions.py, lale/lib/rasl/metrics.py, lale/lib/rasl/min_max_scaler.py, lale/lib/rasl/monoid.py, lale/lib/rasl/project.py, lale/lib/rasl/scores.py, lale/operators.py, lale/type_checking.py, test/test_autoai_ts_libs.py
and update code so it typechecks
=> update pre-commit pyright to version 1.234 

lale/helpers.py
in import_from_sklearn_pipeline
=> force registration of previously known modules

examples/kdd22/08_newops.ipynb
=> Incorporated feedback from Louis to 08_newops.ipynb.

examples/kdd22/README.md
=> Corrected the notebook pointers in kdd22 README.

examples/kdd22/04_imbalance.ipynb
=> Few tweaks to 04_imbalance.ipynb

examples/kdd22/11_directions.ipynb
=> Fix kdd11 kernelspec

lale/lib/lale/hyperopt.py
=> Refactoring of hyperopt.py to make it work with Mac multiprocessing.

lale/__init__.py, setup.py
=> Releasing version 0.6.12.

docs/papers.rst, examples/kdd22/README.md, lale/pretty_print.py
=> Don't pretty-print imports from __main__.

.github/workflows/build.yml, setup.py
=> Trying to pin to a different version of numpy.

.github/workflows/build.yml, setup.py
=> Install numpy before scikit-learn.

.github/workflows/build.yml
=> Comment out test_autoai_output_consumption for the time being.

lale/__init__.py
=> Version 0.6.13.

docs/conf.py, docs/requirements.txt, setup.py
=> Trying to fix readthedocs build problems.

lale/__init__.py
=> Increment version for release.

docs/requirements.txt, setup.py
=> Fix missing bullets in RST as rendered by readthedocs.

lale/__init__.py
=> Incrementing the version to 0.6.16.

docs/papers.rst
=> Added MAPS22 paper to docs/papers.rst.

setup.py
=> Adding typing-extensions to core dependencies.

lale/__init__.py
=> version 0.6.18

setup.py
Signed-off-by: DanielRyszkaIBM <daniel.ryszka@pl.ibm.com>
=> Update aif360, when installing as 'lale[fairness]'

lale/lib/sklearn/decision_tree_classifier.py, lale/lib/sklearn/extra_trees_classifier.py, lale/lib/sklearn/extra_trees_regressor.py, lale/lib/sklearn/hashing_encoder.py, lale/lib/sklearn/random_forest_classifier.py, lale/lib/sklearn/random_forest_regressor.py, lale/lib/sklearn/tfidf_vectorizer.py
=> Fixed some typos in schemas.

lale/helpers.py, lale/lib/lightgbm/lgbm_classifier.py, lale/lib/lightgbm/lgbm_regressor.py, lale/lib/xgboost/xgb_classifier.py, lale/lib/xgboost/xgb_regressor.py
=> In XGB and LGBM, ignore classes fit_param during partial_fit.

lale/__init__.py, lale/datasets/__init__.py, lale/datasets/multitable/__init__.py, lale/datasets/openml/__init__.py, lale/datasets/uci/__init__.py, lale/lib/aif360/__init__.py, lale/lib/autoai_libs/__init__.py, lale/lib/category_encoders/__init__.py, lale/lib/imblearn/__init__.py, lale/lib/lale/__init__.py, lale/lib/lightgbm/__init__.py, lale/lib/rasl/__init__.py, lale/lib/sklearn/__init__.py, lale/lib/snapml/__init__.py, lale/lib/xgboost/__init__.py
by explicitly naming them with as
=> Mark __init__ imports as public for pyright 

lale/lib/sklearn/__init__.py, lale/lib/sklearn/perceptron.py, test/test_core_classifiers.py
=> lale.lib.sklearn.Perceptron

lale/docstrings.py, lale/lib/lightgbm/lgbm_classifier.py, lale/lib/lightgbm/lgbm_regressor.py, lale/lib/sklearn/_common_schemas.py, lale/lib/sklearn/gaussian_nb.py, lale/lib/sklearn/mlp_classifier.py, lale/lib/sklearn/multinomial_nb.py, lale/lib/sklearn/passive_aggressive_classifier.py, lale/lib/sklearn/perceptron.py, lale/lib/sklearn/sgd_classifier.py, lale/lib/sklearn/sgd_regressor.py, lale/lib/xgboost/xgb_classifier.py, lale/lib/xgboost/xgb_regressor.py, lale/operators.py
=> Schemas for partial_fit methods.

lale/__init__.py
=> Version 0.7.0

lale/lib/autoai_libs/date_transformer.py
Signed-off-by: DanielRyszkaIBM <daniel.ryszka@pl.ibm.com>
=> Fix import_from for autoai-libs DateTransformer

lale/lib/sklearn/dummy_classifier.py, lale/lib/sklearn/dummy_regressor.py
=> Fix to DummyRegressor schema.

lale/lib/snapml/batched_tree_ensemble_classifier.py, lale/lib/snapml/batched_tree_ensemble_regressor.py
=> Pandas support for SnapML BatchedTreeEnsembles.

.github/workflows/build.yml, setup.py
Add 3.10 to the master text matrix.  
Change PR default python version to 3.9
=> CI: update Python versions

.github/workflows/build.yml, .pre-commit-config.yaml
CI: Re-enable static checks on Python 3.7
=> Update static checker versions.

.github/workflows/build.yml, .github/workflows/release.yml
=> Update CI release action

.github/workflows/build.yml, setup.py
=> Update aif360 version in kdd target

lale/helpers.py, lale/lib/sklearn/one_hot_encoder.py
=> Change scipy.sparse.csr.csr_matrix to scipy.sparse.csr_matrix

lale/lib/aif360/util.py
=> Improved count_fairness_groups.

.github/workflows/build.yml, lale/lib/category_encoders/__init__.py, lale/lib/category_encoders/target_encoder.py, test/test_category_encoders.py
=> Added category_encoders.TargetEncoder.

.pre-commit-config.yaml, lale/expressions.py, lale/lib/lale/hyperopt.py, lale/lib/rasl/batching.py, lale/lib/rasl/datasets.py, lale/lib/rasl/metrics.py, lale/operators.py, lale/search/schema2search_space.py, lale/util/numpy_to_torch_dataset.py, lale/util/numpy_torch_dataset.py
=> Update pyright version

lale/helpers.py, test/test_autoai_output_consumption.py
=> Move println_pos from helpers to the test that uses it

test/test_autoai_output_consumption.py
=> remove use of os.system from _println_pos

.pre-commit-config.yaml, README.md, bandit.yaml, lale/datasets/movie_review.py, lale/datasets/multitable/fetch_datasets.py, lale/datasets/openml/openml_datasets.py, lale/datasets/uci/uci_datasets.py, lale/docstrings.py, lale/grammar.py, lale/lib/aif360/datasets.py, lale/lib/autoai_libs/fs1.py, lale/lib/autoai_libs/fs2.py, lale/search/PGO.py, lale/util/VisitorMeta.py, test/test_pipeline.py, test/test_relational_sklearn.py
=> Add bandit support

lale/datasets/multitable/fetch_datasets.py, lale/helpers.py, lale/json_operator.py, lale/lib/aif360/disparate_impact_remover.py, lale/lib/lale/time_series_transformer.py, lale/lib/rasl/hashing_encoder.py, lale/lib/sklearn/ordinal_encoder.py, lale/operators.py, lale/search/schema2search_space.py, pylintrc, test/test_category_encoders.py, test/test_core_classifiers.py, test/test_core_misc.py, test/test_core_pipeline.py, test/test_core_transformers.py, test/test_optimizers.py, test/test_relational.py, test/test_relational_sklearn.py, test/test_type_checking.py
=> enable pylint unused-variable warning

setup.py
=> Add license and classifiers to package metadata

.github/workflows/build.yml
=> Install autoai_libs when testing the demo notebooks on master

.github/workflows/build.yml
=> update version of checkout and setup-python build actions

lale/lib/aif360/adversarial_debiasing.py, lale/lib/lale/both.py, lale/lib/lale/identity_wrapper.py, lale/lib/lale/observing.py, lale/lib/lale/optimize_last.py, lale/lib/sklearn/fit_spec_proxy.py
=> Even on impl classes, fit should return self.

docs/requirements.txt
=> Add dependency to docs/requirements.txt

docs/requirements.txt
=> Add smac to docs requirements

test/test_aif360.py
=> Relax test_fair_smote_pd_num threshold.

lale/lib/autoai_libs/boolean2float.py, lale/lib/autoai_libs/cat_encoder.py, lale/lib/autoai_libs/cat_imputer.py, lale/lib/autoai_libs/column_selector.py, lale/lib/autoai_libs/compress_strings.py, lale/lib/autoai_libs/date_transformer.py, lale/lib/autoai_libs/float32_transform.py, lale/lib/autoai_libs/float_str2_float.py, lale/lib/autoai_libs/fs1.py, lale/lib/autoai_libs/fs2.py, lale/lib/autoai_libs/num_imputer.py, lale/lib/autoai_libs/numpy_column_selector.py, lale/lib/autoai_libs/numpy_permute_array.py, lale/lib/autoai_libs/numpy_replace_missing_values.py, lale/lib/autoai_libs/numpy_replace_unknown_values.py, lale/lib/autoai_libs/opt_standard_scaler.py, lale/lib/autoai_libs/t_no_op.py, lale/lib/autoai_libs/ta1.py, lale/lib/autoai_libs/ta2.py, lale/lib/autoai_libs/tam.py, lale/lib/autoai_libs/tb1.py, lale/lib/autoai_libs/text_transformer.py, lale/lib/autoai_libs/tgen.py, lale/lib/autoai_libs/word2vec_transformer.py
=> Simplify/normalize autoai_libs impl class __init__ methods

lale/lib/sklearn/ada_boost_classifier.py, lale/lib/sklearn/ada_boost_regressor.py, lale/lib/sklearn/bagging_classifier.py, lale/lib/sklearn/bagging_regressor.py
=> simplify constructors of sklearn bagging/boosting classes

lale/helpers.py, lale/lib/sklearn/ada_boost_classifier.py, lale/lib/sklearn/ada_boost_regressor.py, lale/lib/sklearn/bagging_classifier.py, lale/lib/sklearn/bagging_regressor.py
=> Fixup how we find the base_estimator/estimator

.pre-commit-config.yaml, lale/lib/aif360/adversarial_debiasing.py, lale/lib/rasl/__init__.py, lale/lib/rasl/_util.py, lale/lib/rasl/hashing_encoder.py, lale/lib/rasl/target_encoder.py, test/test_relational_sklearn.py
=> TargetEncoder as a Monoid.

.github/workflows/build.yml, .pre-commit-config.yaml, lale/datasets/uci/uci_datasets.py
=> Update versions of pre_commit tools

lale/datasets/data_schemas.py, test/test_relational.py
=> Change data_schemas.to_schema to directly compile spark schema 

.github/workflows/release.yml
=> Update deploy action to use newer action versions

lale/__init__.py
* Rewrite import_from_sklearn_pipeline, reducing copying and calls to set_params
* update black version used for formatting code to 2023 standard
* Improvements to monoidal TargetEnoder implementation
* minor improvement to task graph code
=> Version 0.7.5

lale/lib/aif360/util.py, test/test_aif360.py
=> bool labels for AIF360

lale/lib/autogen/multi_task_lasso_cv.py, lale/lib/sklearn/logistic_regression.py
=> Some more sklearn 1.2 changes.

lale/lib/autogen/linear_regression.py, lale/lib/autogen/multi_task_elastic_net.py, lale/lib/autogen/multi_task_elastic_net_cv.py, lale/lib/autogen/multi_task_lasso.py, lale/lib/autogen/multi_task_lasso_cv.py
=> More sklearn 1.2 schema changes.

.github/workflows/build.yml
Remove actions that are forbidden by org policy
=> CI: Adjust actions

lale/__init__.py
- Improvements to CI 
- more static checking
- only using trusted actions
- Improvements to aif360 schemas and derived operators
- Update SnapML schemas for new version
- loosen scipy release bounds
=> Increment lale version to 0.7.7

.pre-commit-config.yaml, docs/index.rst, docs/requirements.txt, lale/datasets/movie_review.py, lale/lib/autoai_libs/_common_schemas.py, lale/lib/autoai_libs/cat_encoder.py, lale/lib/autoai_libs/cat_imputer.py, lale/lib/autoai_libs/float_str2_float.py, lale/lib/autoai_libs/fs2.py, lale/lib/autoai_libs/num_imputer.py, lale/lib/autoai_libs/numpy_replace_missing_values.py, lale/lib/autoai_libs/t_no_op.py, lale/lib/autoai_libs/tgen.py, lale/lib/rasl/task_graphs.py, setup.py, test/test_json_pretty_viz.py
=> Force pretty_print for hyperparams that are **kwarg in the wrapper but positional in the impl.

lale/__init__.py
- Updates to autoai_libs schemas to improve pretty-printing
- Update version of static checkers
=> Increment version to 0.7.8

lale/lib/autoai_libs/__init__.py, lale/lib/autoai_libs/nsfa.py
- schema and wrapper for new autoai_libs transformer NSFA
=> Wrapper for autoai_libs.nsfa transformer added

lale/__init__.py
* Relax some dependency upper bounds
* Add RandomUnderSampler from imblearn
* Add Orbis and Urbis Mystic implementations
* Add 7 more fairness datasets
* Documentation improvements
* Add wrapper for autoai_libs.nsfa transformer
=> Increment lale version to 0.7.9

lale/__init__.py
* guard import of mystic
* add upper bound to tensorflow dependency
* remove protobuf installation version constraint.
=> Increment lale version to 0.7.10

lale/__init__.py, setup.py
* Fix documentation links in visualization
* changed nbviewer links to point at github instead
=> Increment lale version to 0.7.11

docs/requirements.txt, lale/lib/autogen/fast_ica.py, lale/lib/autogen/mini_batch_sparse_pca.py, lale/lib/autogen/sparse_pca.py, lale/lib/sklearn/__init__.py, lale/lib/sklearn/target_encoder.py, test/test_core_transformers.py
=> Add TargetEncoder wrapper (as of scikit-learn 1.3)

lale/__init__.py
* Add support for hyperopt 0.2.7
=> Increment lale version to 0.8.4
